[project]
name = "pygame-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
    "pygame-menu>=4.5.2",
]

[project.scripts]
init = "main:main"
